server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:33061/db_insumos?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true