server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:33065/db_citas?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

# URLs de Feign Clients para entorno local (IDE)
paciente.service.url: http://localhost:8082/pacientes
odontologo.service.url: http://localhost:8083/odontologos
