server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:33064/db_tratamientos?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true